[package]
authors = ["Sergey Sova <mail@sergeysova.com>"]
edition = "2018"
name = "openapi-hooks"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openapi-resolver = "0.1.0"
openapiv3 = "0.3.2"
